export const recommendedItems = [
  {
    name: "Filter Kit",
    image: "/images/filter-kit.jpg",
    description: "Comprehensive filter kit for air, oil, and fuel filtration—ideal for regular engine maintenance.",
    price: "$29.99",
    rating: 4.5,
    experience: "Improved engine performance after using it.",
    expiry: "2026-12-31",
  },
  {
    name: "Spare Motor",
    image: "/images/spare-motor.jpg",
    description: "Reliable replacement motor, compatible with most mid-size vehicles.",
    price: "$249.00",
    rating: 4.3,
    experience: "Good backup option for emergencies.",
    expiry: null, // durable item, no expiry
  },
  {
    name: "Oil Can",
    image: "/images/oil-can.jpg",
    description: "Steel oil can with a long spout for precise lubrication.",
    price: "$12.50",
    rating: 4.7,
    experience: "Perfect for workshop lubrication.",
    expiry: null,
  },
  {
    name: "Air Compressor",
    image: "/images/air-compressor.jpg",
    description: "Portable air compressor with LED display and auto shut-off.",
    price: "$89.00",
    rating: 4.6,
    experience: "Efficient and compact design.",
    expiry: null,
  },
  {
    name: "Hydraulic Jack",
    image: "/images/hydraulic-jack.jpg",
    description: "3-ton hydraulic jack for SUVs and sedans.",
    price: "$65.00",
    rating: 4.8,
    experience: "Strong build and reliable.",
    expiry: null,
  },
  {
    name: "Toolbox Set",
    image: "/images/toolbox-set.jpg",
    description: "80-piece mechanic’s tool set with socket wrenches, pliers, and more.",
    price: "$79.99",
    rating: 4.4,
    experience: "Great starter toolkit.",
    expiry: null,
  },
  {
    name: "Spark Plug",
    image: "/images/spark-plug.jpg",
    description: "High-performance iridium spark plug.",
    price: "$8.95",
    rating: 4.6,
    experience: "Better startup and efficiency.",
    expiry: "2027-06-01",
  },
  {
    name: "Cooling Fan",
    image: "/images/cooling-fan.jpg",
    description: "Electric radiator cooling fan with low noise output.",
    price: "$42.00",
    rating: 4.2,
    experience: "Quiet and effective.",
    expiry: null,
  },
  {
    name: "Brake Pads",
    image: "/images/brake-pads.jpg",
    description: "Semi-metallic front brake pads with optimized stopping power.",
    price: "$34.50",
    rating: 4.7,
    experience: "Smooth and responsive braking.",
    expiry: "2026-10-30",
  },
];
